version: '3.0'
services:
  web:
    container_name: web
    build: 
        context: ../Backend
        dockerfile: ../Docker/web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Linux
    ports:
      - 9000:9000
    volumes:
      - G:/Data:/Data
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - G:/Data/Elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
